// Pure planner logic for the Discord bot. No DB calls, no Anthropic, no I/O —
// the bot's API routes pass in already-loaded rows and these functions decide
// what to surface. Kept pure so it's unit-testable the same way the scorer is.
import type { Task, Goal } from "@/db/schema";
import { score, sortByScore } from "@/features/tasks/scorer";

const HOUR = 1000 * 60 * 60;
const DAY = HOUR * 24;

// Windows (hours / days) — tuned conservatively for "calm" accountability.
export const DUE_SOON_HOURS = 2; // start_at within the next 2h
export const OVERDUE_GRACE_HOURS = 24; // start_at passed within the last 24h → one "just slipped" ping
export const SLIPPING_OVERDUE_DAYS = 1; // overdue by ≥1 day → shows in the daily digest
export const GOAL_IDLE_DAYS = 7; // goal with no completion in 7d → "idle"

export type DueKind = "due_soon" | "overdue";

export type CompactTask = {
  id: number;
  title: string;
  categories: string[];
  urgency: number | null;
  importance: number | null;
  estTimeMin: number | null;
  focus: string | null;
  startAt: string | null;
  goalId: number | null;
  score: number;
};

export type IdleGoal = { id: number; name: string; idleDays: number };

export type Digest = {
  top: CompactTask[];
  overdueTasks: CompactTask[];
  idleGoals: IdleGoal[];
};

export type ProgressStats = {
  sinceDays: number;
  completed: number;
  created: number;
  open: number;
  overdueOpen: number;
  idleGoals: number;
};

export function toCompact(task: Task, now: Date): CompactTask {
  return {
    id: task.id,
    title: task.title,
    categories: task.categories,
    urgency: task.urgency,
    importance: task.importance,
    estTimeMin: task.estTimeMin,
    focus: task.focus,
    startAt: task.startAt ? task.startAt.toISOString() : null,
    goalId: task.goalId,
    score: Number(score(task, now).toFixed(3)),
  };
}

const isOpen = (t: Task) => t.doneAt === null;

/**
 * Classify a single task's `start_at` relative to now. Returns a reminder kind
 * only inside a window — `due_soon` for the next couple hours, `overdue` for the
 * grace period just after it slipped. Drives the bot's due-soon ticks.
 */
export function dueWindow(task: Task, now: Date): DueKind | null {
  if (!isOpen(task) || !task.startAt) return null;
  const hoursUntil = (task.startAt.getTime() - now.getTime()) / HOUR;
  if (hoursUntil > 0 && hoursUntil <= DUE_SOON_HOURS) return "due_soon";
  if (hoursUntil <= 0 && hoursUntil >= -OVERDUE_GRACE_HOURS) return "overdue";
  return null;
}

/** Goals that own at least one open task, are older than the idle window, and
 *  have had no task completed within it. Fresh goals are never flagged. */
export function idleGoals(tasks: Task[], goals: Goal[], now: Date): IdleGoal[] {
  const out: IdleGoal[] = [];
  for (const goal of goals) {
    const goalTasks = tasks.filter((t) => t.goalId === goal.id);
    const hasOpen = goalTasks.some(isOpen);
    if (!hasOpen) continue;
    if (now.getTime() - goal.createdAt.getTime() < GOAL_IDLE_DAYS * DAY) continue;

    const lastDone = goalTasks
      .map((t) => t.doneAt)
      .filter((d): d is Date => d !== null)
      .reduce<number | null>((max, d) => Math.max(max ?? 0, d.getTime()), null);

    const idleSince = lastDone ?? goal.createdAt.getTime();
    const idleDays = Math.floor((now.getTime() - idleSince) / DAY);
    if (idleDays >= GOAL_IDLE_DAYS) out.push({ id: goal.id, name: goal.name, idleDays });
  }
  return out;
}

/** Today's plan + what's slipping. Pure; the bot formats this into Discord text. */
export function buildDigest(tasks: Task[], goals: Goal[], now: Date): Digest {
  const open = tasks.filter(isOpen);
  const top = sortByScore(open, now)
    .slice(0, 3)
    .map((t) => toCompact(t, now));

  const overdueTasks = open
    .filter((t) => t.startAt !== null && now.getTime() - t.startAt.getTime() >= SLIPPING_OVERDUE_DAYS * DAY)
    .sort((a, b) => a.startAt!.getTime() - b.startAt!.getTime())
    .map((t) => toCompact(t, now));

  return { top, overdueTasks, idleGoals: idleGoals(tasks, goals, now) };
}

/** Counts over a recent window for the "how am I doing?" read. The prose summary
 *  is generated by Anthropic from these numbers — this part stays deterministic. */
export function buildProgressStats(
  tasks: Task[],
  goals: Goal[],
  now: Date,
  sinceDays: number
): ProgressStats {
  const since = now.getTime() - sinceDays * DAY;
  const open = tasks.filter(isOpen);
  return {
    sinceDays,
    completed: tasks.filter((t) => t.doneAt !== null && t.doneAt.getTime() >= since).length,
    created: tasks.filter((t) => t.createdAt.getTime() >= since).length,
    open: open.length,
    overdueOpen: open.filter((t) => t.startAt !== null && t.startAt.getTime() < now.getTime()).length,
    idleGoals: idleGoals(tasks, goals, now).length,
  };
}
